image: python:3.7
script:
  - pip install pip tox -U --no-cache-dir
  - tox -p all

notify:
  slack:
    webhook_url: $$S_WEBHOOK_URL
    username: 'drone'
    channel: '#arche-deployments'
    on_started: false
    on_success: false
    on_failure: true
